### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by littlebtc** [turner-industries/formik-semantic-ui#11]
I had made a quick (and maybe incorrect) implementation of the TypeScript type definition:

https://gist.github.com/littlebtc/0effc6ab4cec4a56346b1bd877238424

I think it is better to include an official type definition as I am switching to TypeScript development and I am trying to use this library.

**Comment by justinobney** [comment]
@littlebtc That is a great idea. Someone from the @turner-industries/dev-team will have a look at it. Thanks!

**Comment by danpfe** [comment]
Hi guys, I'll shamelessly hijack this thread.

@littlebtc I took the liberty to take your Gist, touched it up a little and have it deployed together with the library itself.

@justinobney In all honesty I have to admit I am not sure that rollup-plugin-copy would be the "formal" way to have typings distributed with a library (am a bit new to TypeScript), but from my testing it seems to get the job done and my TypeScript-project detects the typings.

If you guys find it useful please accept this new PR as well. =)

**Comment by justinobney** [comment]
@jsmichot ?

**Comment by danpfe** [comment]
@littlebtc @justinobney I guess this issue can be closed now that the typings are merged and released?
