### ISSUE TITLE
Different versions on NPM and on Github

### ISSUE THREAD

**Issue by danpfe** [turner-industries/formik-semantic-ui#14]
Hi guys,

I noticed that version 0.9.0 of your lib is available on NPM but the latest version on GitHub seems to be 0.8.2. Is there a good reason why the source for v0.9.0 isn't available?

Also, I created a fork where I added those changes present on NPM into your code and fixed the tests so the framework can be built against semantic-ui-react all the way to the latest version 0.86.0 (https://github.com/danpfe/formik-semantic-ui) but before I continue working I just wanted to get some clarity on the specific versioning-issue.

Thanks!
/D

**Comment by justinobney** [comment]
Just an oversight on my part.


________________________________

**Comment by danpfe** [comment]
Hi Justin, good to hear, was a little concerned the project might be abandoned. I'd like to offer a PR from my local fork where I've done a little bit of cleanup and testing which I hope helps you guys out to push a newer release.

**Comment by danpfe** [comment]
Thanks for accepting my PR. Closing this issue.
