### ISSUE TITLE
how to customize errors?

### ISSUE THREAD

**Issue by mehrad77** [turner-industries/formik-semantic-ui#17]
So now for every error in validation of filed we get something like:
```html
<span class="sui-error-message">Field is empety.</span>
```
how can add some custom calsses to this? is it possible?

**Comment by justinobney** [comment]
@mehrad77 feel free to submit a PR. If not I will look at it when i get a chance.

**Comment by michelts** [comment]
Hi @mehrad77 

I done it using pure less. For instance, the cove bellow change the message to a fancy pointing label:

```
.sui-error-message {
  &:extend(.ui.pointing.label, .ui.basic.poiting.label, .ui.label, .ui.basic.label, .ui.basic.red.label, .ui.red.label);                                                       

  &:before {
    &:extend(.ui.pointing.label:before, .ui.basic.poiting.label:before);
  }
}
```

It will render something like:

![image](https://user-images.githubusercontent.com/361492/62326236-0095a280-b484-11e9-9ea8-67cbef036818.png)

Anyway, I've sent a pull request to allow customize the error component. I would be glad to hear your opinion @justinobney :)
