### ISSUE TITLE
Cannot dynamically setFieldValue for Input.

### ISSUE THREAD

**Issue by 1323** [turner-industries/formik-semantic-ui#7]
I was trying to calculate value in Input B based on Input A, times other value, but I couldn't find solution better than extending onChange callback parameters list. 

My solution was to return form instance in onChange callback:
`onChange={(e, {name, value}) => {
                setFieldValue(form, name, value, false);
                Promise
                  .resolve()
                  .then(() => {
                    onChange && onChange(e, {name, value, form});
                  });
}}` 

and then use form.setFieldValue inside my own onChange callback.
If it is the best solution, I could make a PR.

Thanks in advance, great idea with making this repository,

**Comment by justinobney** [comment]
@1323 There is currently a way to use render props to get access to the form. Would this solve your problem?

Example use case: https://codesandbox.io/s/1vrpoqxpp4

**Comment by 1323** [comment]
@justinobney yeah, superb right now it has satisfied my needs.
Thank for help
